version: "3.8"
services:

  ingredient_mongodb:
    hostname: ingredient_mongodb
    image: mongo:latest
    command: mongod --port 27027
    environment:
      MONGO_INITDB_ROOT_USERNAME: hakan
      MONGO_INITDB_ROOT_PASSWORD: kay1983nar
      MONGO_INITDB_DATABASE: ingredient
    ports:
      - 27027:27027
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - product-network

  ingredient_elastic:
    image: elasticsearch:7.10.1
    hostname: ingredient_elastic
    ports:
      - 9200:9200
    environment:
      node.name: elasticsearch
      discovery.type: single-node
    networks:
      - product-network

  ingredient-api:
    depends_on:
      - ingredient_mongodb
      - ingredient_elastic
    image: hakankaynar/ingredient:latest
    ports:
      - 8081:8081
    networks:
      - product-network

networks:
  product-network:
    name: product-network
    attachable: true
